apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-zmmgp-headsez-trans
  title: silver_sap_cleansed.zmmgp_headsez_trans
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.zmmgp_headsez_trans\n\
    Layer: silver-cleansed\nColumns (192):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data\
    \ Services-generated integer for sequencing\n  - DI_OPERATION_TYPE (string) --\
    \ Data Services-generated row operation type\n  - MANDT (string) -- Client\n \
    \ - GPNO (string) -- Gate Pass No.\n  - TOKENNO (string) -- Token No\n  - INWARDTYPE\
    \ (string) -- Inward Type\n  - LOCIMP (string) -- Local/Imported Mat.\n  - GATEGROUP\
    \ (string) -- Gate Group\n  - GPREFNO (string) -- Parent Gate Pass No.\n  - OUTGPNO\
    \ (string) -- Gate Pass No.\n  - GPDT (date) -- Date on which the gate pass was\
    \ created\n  - GINTIME (string) -- Gate In Time\n  - GINDATE (date) -- Gate In\
    \ Date\n  - COMPPLANT (string) -- Plant\n  - COMPSLOC (string) -- Storage Location\n\
    \  - GATE (string) -- Gate No.\n  - EBELN (string) -- Purchasing Document\n  -\
    \ VBELN (string) -- Billing Document\n  - ERDAT (date) -- Created on\n  - ARE1NO\
    \ (string) -- ARE 1 No.\n  ... +172 more\nDiscovered: 2026-04-30 12:29"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.zmmgp_headsez_trans
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: zmmgp_headsez_trans
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/zmmgp_headsez_trans
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
