apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-eqst-trans
  title: silver_sap_cleansed.eqst_trans
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.eqst_trans\n\
    Layer: silver-cleansed\nColumns (27):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data\
    \ Services-generated integer for sequencing\n  - DI_OPERATION_TYPE (string) --\
    \ Data Services-generated row operation type\n  - MANDT (string) -- Client\n \
    \ - EQUNR (string) -- Equipment\n  - WERKS (string) -- Plant\n  - STLAN (string)\
    \ -- BOM Usage\n  - STLNR (string) -- Bill of material\n  - STLAL (string) --\
    \ Alternative BOM\n  - ANDAT (date) -- Created on\n  - ANNAM (string) -- Created\
    \ by\n  - AEDAT (date) -- Changed on\n  - AENAM (string)\n  - ODQ_CHANGEMODE (string)\
    \ -- Change Mode for a Data Record in the Delta\n  - ODQ_ENTITYCNTR (double) --\
    \ Number of Data Units (Data Records for Example)\n  - DI_TIMESTAMP (timestamp)\n\
    \  - SYS_INGESTION_DATE (date)\n  - SYS_FILE_NAME (string)\n  - SYS_MODIFIED_TIME\
    \ (timestamp)\n  - IDENTIFIER (string)\n  - HASH_KEY (string)\n  ... +7 more\n\
    Discovered: 2026-04-30 12:24"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.eqst_trans
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: eqst_trans
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/eqst_trans
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
