apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-tj02t-mstr
  title: silver_sap_cleansed.tj02t_mstr
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.tj02t_mstr\n\
    Layer: silver-cleansed\nColumns (22):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data\
    \ Services-generated integer for sequencing\n  - DI_OPERATION_TYPE (string) --\
    \ Data Services-generated row operation type\n  - ISTAT (string) -- System status\n\
    \  - SPRAS (string) -- Language Key\n  - TXT04 (string) -- Status\n  - TXT30 (string)\n\
    \  - ODQ_CHANGEMODE (string) -- Change Mode for a Data Record in the Delta\n \
    \ - ODQ_ENTITYCNTR (double) -- Number of Data Units (Data Records for Example)\n\
    \  - DI_TIMESTAMP (timestamp)\n  - SYS_INGESTION_DATE (date)\n  - SYS_FILE_NAME\
    \ (string)\n  - SYS_MODIFIED_TIME (timestamp)\n  - IDENTIFIER (string)\n  - HASH_KEY\
    \ (string)\n  - _errors (array<struct<name:string,message:string,columns:array<string>,filter:string,function:string,run_time:timestamp,run_id:string,user_metadata:map<string,string>>>)\n\
    \  - _warnings (array<struct<name:string,message:string,columns:array<string>,filter:string,function:string,run_time:timestamp,run_id:string,user_metadata:map<string,string>>>)\n\
    \  - error_codes (array<string>)\n  - warn_codes (array<string>)\n  - SYS_EFFECTIVE_START_DATE\
    \ (date)\n  - SYS_EFFECTIVE_END_DATE (date)\n  ... +2 more\nDiscovered: 2026-04-30\
    \ 12:28"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.tj02t_mstr
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: tj02t_mstr
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/tj02t_mstr
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
  dependsOn:
  - component:bronze-sap-mul-tj02t-slt
