apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-cdhdr-trans
  title: silver_sap_cleansed.cdhdr_trans
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.cdhdr_trans\n\
    Layer: silver-cleansed\nColumns (32):\n  - MANDANT (string)\n  - OBJECTCLAS (string)\n\
    \  - OBJECTID (string)\n  - CHANGENR (string)\n  - USERNAME (string)\n  - UDATE\
    \ (date)\n  - UTIME (string)\n  - TCODE (string)\n  - PLANCHNGNR (string)\n  -\
    \ ACT_CHNGNO (string)\n  - WAS_PLANND (string)\n  - CHANGE_IND (string)\n  - LANGU\
    \ (string)\n  - VERSION (string)\n  - _DATAAGING (date)\n  - SYS_INGESTION_DATE\
    \ (date)\n  - SYS_FILE_NAME (string)\n  - SYS_MODIFIED_TIME (timestamp)\n  - DI_TIMESTAMP\
    \ (timestamp)\n  - IDENTIFIER (string)\n  ... +12 more\nDiscovered: 2026-04-30\
    \ 12:24"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.cdhdr_trans
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: cdhdr_trans
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/cdhdr_trans
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
