apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-wcagns-trans
  title: silver_sap_cleansed.wcagns_trans
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.wcagns_trans\n\
    Layer: silver-cleansed\nColumns (33):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data\
    \ Services-generated integer for sequencing\n  - DI_OPERATION_TYPE (string) --\
    \ Data Services-generated row operation type\n  - MANDT (string) -- Client\n \
    \ - OBJNR (string) -- Object number\n  - COUNTER (bigint) -- Counter\n  - COUNTERS\
    \ (bigint) -- Counter\n  - GENNAME (string) -- Entered by\n  - GENDATUM (date)\
    \ -- Created on\n  - GENTIME (string) -- Entered At\n  - GENVDATE (date) -- App.fr\
    \ date\n  - GENBDATE (date) -- App.to date\n  - GENVTIME (string) -- Entered At\n\
    \  - GENBTIME (string) -- AppToTime\n  - GENINAME (string) -- Deactivated by\n\
    \  - GENIDATE (date) -- Deactivated on\n  - GENITIME (string) -- Deactivated at\n\
    \  - GENIAKT (string) -- Permit inactive\n  - GENVNAME (string)\n  - ODQ_CHANGEMODE\
    \ (string) -- Change Mode for a Data Record in the Delta\n  - ODQ_ENTITYCNTR (double)\
    \ -- Number of Data Units (Data Records for Example)\n  ... +13 more\nDiscovered:\
    \ 2026-04-30 12:29"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.wcagns_trans
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: wcagns_trans
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/wcagns_trans
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
