apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-imptt-mstr
  title: silver_sap_cleansed.imptt_mstr
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.imptt_mstr\n\
    Layer: silver-cleansed\nColumns (76):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data\
    \ Services-generated integer for sequencing\n  - DI_OPERATION_TYPE (string) --\
    \ Data Services-generated row operation type\n  - MANDT (string) -- Client\n \
    \ - POINT (string) -- Measuring point\n  - MPOBJ (string) -- OBjNo.MeasPointObj.\n\
    \  - PSORT (string) -- Measurement position\n  - PSORTR (string) -- RefMeasPosition\n\
    \  - PTTXT (string) -- Description\n  - MLANG (string) -- Language Key\n  - KZLTX\
    \ (string) -- Long text exists\n  - MPTYP (string) -- MeasPointCategory\n  - IRFMP\
    \ (string) -- RefMeasuringPoint\n  - ERDAT (date) -- Created on\n  - ERNAM (string)\
    \ -- Created by\n  - AEDAT (date) -- Changed on\n  - AENAM (string) -- Changed\
    \ by\n  - BEGRU (string) -- AuthorizGroup\n  - INACT (string) -- MeasPoint inactive\n\
    \  - LVORM (string) -- Deletion flag\n  - LOCAS (string) -- Assembly\n  ... +56\
    \ more\nDiscovered: 2026-04-30 12:25"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.imptt_mstr
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: imptt_mstr
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/imptt_mstr
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
