apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-csks-mstr
  title: silver_sap_cleansed.csks_mstr
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.csks_mstr\n\
    Layer: silver-cleansed\nColumns (101):\n  - MANDT (string)\n  - KOKRS (string)\n\
    \  - KOSTL (string)\n  - DATBI (date)\n  - DATAB (date)\n  - BKZKP (string)\n\
    \  - PKZKP (string)\n  - BUKRS (string)\n  - GSBER (string)\n  - KOSAR (string)\n\
    \  - VERAK (string)\n  - VERAK_USER (string)\n  - WAERS (string)\n  - KALSM (string)\n\
    \  - TXJCD (string)\n  - PRCTR (string)\n  - WERKS (string)\n  - LOGSYSTEM (string)\n\
    \  - ERSDA (date)\n  - USNAM (string)\n  ... +81 more\nDiscovered: 2026-04-30\
    \ 12:24"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.csks_mstr
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: csks_mstr
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/csks_mstr
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
  dependsOn:
  - component:bronze-sap-mul-csks-slt
