apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-t077d-mstr
  title: silver_sap_cleansed.t077d_mstr
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.t077d_mstr\n\
    Layer: silver-cleansed\nColumns (37):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data\
    \ Services-generated integer for sequencing\n  - DI_OPERATION_TYPE (string) --\
    \ Data Services-generated row operation type\n  - MANDT (string) -- Client\n \
    \ - KTOKD (string) -- Account group\n  - FAUSA (string) -- FAUSA\n  - FAUSF (string)\
    \ -- FAUSF\n  - FAUSV (string) -- Sales data\n  - NUMKR (string) -- Number range\n\
    \  - XCPDS (string) -- One-time account\n  - KALSM (string) -- Output determ.proc.\n\
    \  - DEAR1 (string) -- Competitors\n  - DEAR2 (string) -- Sales partners\n  -\
    \ DEAR3 (string) -- Prospect\n  - DEAR4 (string) -- Customer type 4\n  - DEAR5\
    \ (string) -- Default sold-to pty\n  - FAUS1 (string) -- FAUS1\n  - FAUSW (string)\
    \ -- FieldStatus plant\n  - FAUSG (string) -- FAUSG\n  - DEAR6 (string) -- Consumer\n\
    \  - FAUS2 (string) -- FAUS2\n  ... +17 more\nDiscovered: 2026-04-30 12:27"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.t077d_mstr
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: t077d_mstr
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/t077d_mstr
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
  dependsOn:
  - component:bronze-sap-mul-t077d-slt
