apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-sap-cleansed-j-1imovend-trans
  title: silver_sap_cleansed.j_1imovend_trans
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver_sap_cleansed.j_1imovend_trans\n\
    Layer: silver-cleansed\nColumns (82):\n  - MANDT (string)\n  - LIFNR (string)\n\
    \  - J_1IEXCD (string)\n  - J_1IEXRN (string)\n  - J_1IEXRG (string)\n  - J_1IEXDI\
    \ (string)\n  - J_1IEXCO (string)\n  - J_1ICSTNO (string)\n  - J_1ILSTNO (string)\n\
    \  - J_1IPANNO (string)\n  - J_1IEXCIVE (string)\n  - J_1ISSIST (string)\n  -\
    \ J_1IVTYP (string)\n  - J_1IVENCRE (string)\n  - AEDAT (date)\n  - USNAM (string)\n\
    \  - J_1ISERN (string)\n  - J_1IPANREF (string)\n  - J_1IPANVALDT (date)\n  -\
    \ J_1I_CUSTOMS (string)\n  ... +62 more\nDiscovered: 2026-04-30 12:25"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver-cleansed
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver_sap_cleansed.j_1imovend_trans
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver_sap_cleansed
    databricks.com/table: j_1imovend_trans
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver_sap_cleansed/j_1imovend_trans
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
