apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: edl-catalog
  description: All EDL Platform Components
spec:
  targets:
    - ./systems/edl-system.yaml
    - ./components/bronze-layer.yaml
    - ./components/silver-cleansed.yaml
    - ./components/silver-er.yaml
    - ./components/gold-layer.yaml
    - ./components/dashboards.yaml
    - ./components/data-product-api.yaml
    - ./components/cicd-pipeline.yaml
    - ./resources/databricks-workspace.yaml