site_name: Enterprise Data Lake Documentation
repo_url: ''
edit_uri: ''
plugins:
  - techdocs-core
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Data Model: data-model.md
  - Onboarding: onboarding.md