apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-ariba-auction-predecessor-projectid-new-schema
  title: bronze_ariba.auction_predecessor_projectid_new_schema
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_ariba.auction_predecessor_projectid_new_schema\n\
    Columns (37):\n  - LOADING_STATUS (string)\n  - TRANSFER_TIMESTAMP (string)\n\
    \  - beginDate (string)\n  - businessSystem_documentType_key (string)\n  - businessSystem_documentType_value\
    \ (string)\n  - businessSystem_purchasingGroup_key (string)\n  - businessSystem_purchasingGroup_value\
    \ (string)\n  - businessSystem_purchasingOrganization_key (string)\n  - businessSystem_purchasingOrganization_value\
    \ (string)\n  - createDate (string)\n  - currency (string)\n  - departments_name\
    \ (string)\n  - departments_uniqueName (string)\n  - description (string)\n  -\
    \ displayVersion (string)\n  ... +22 more\nDiscovered: 2026-04-30 11:24"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_ariba.auction_predecessor_projectid_new_schema
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_ariba
    databricks.com/table: auction_predecessor_projectid_new_schema
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_ariba/auction_predecessor_projectid_new_schema
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
