apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-mul-afvc-slt
  title: bronze_sap_mul.afvc_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_mul.afvc_slt\n\
    Layer: bronze\nColumns (200):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data Services-generated\
    \ integer for sequencing\n  - DI_OPERATION_TYPE (string) -- Data Services-generated\
    \ row operation type\n  - MANDT (string) -- Client\n  - AUFPL (bigint) -- Opertn\
    \ Task List No.\n  - APLZL (bigint) -- Counter\n  - PLNFL (string) -- Sequence\n\
    \  - PLNKN (bigint) -- Task list node\n  - PLNAL (string) -- Group Counter\n \
    \ - PLNTY (string) -- Task List Type\n  - VINTV (bigint) -- Operation increment\n\
    \  - PLNNR (string) -- Group\n  - ZAEHL (bigint) -- Counter\n  - VORNR (string)\
    \ -- Activity\n  - STEUS (string) -- Control Key\n  - ARBID (bigint) -- Object\
    \ ID\n  - PDEST (string) -- Printer\n  - WERKS (string) -- Plant\n  - KTSCH (string)\
    \ -- Standard text key\n  - LTXA1 (string) -- Operation Short Text\n  - LTXA2\
    \ (string) -- Description\n  ... +180 more\nDiscovered: 2026-04-30 12:19"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - mul
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_mul.afvc_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_mul
    databricks.com/table: afvc_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_mul/afvc_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
