apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-dwh-sap-big-6-spend
  title: bronze_dwh_sap.big_6_spend
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_dwh_sap.big_6_spend\n\
    Columns (13):\n  - Inst (string)\n  - Co_Code (string)\n  - Vendor_Code (string)\n\
    \  - Vendor_Name (string)\n  - Posting_Date (string)\n  - Amount (string)\n  -\
    \ FY (string)\n  - BU (string)\n  - Department (string)\n  - Description_2 (string)\n\
    \  - Amt_in_Lakhs (string)\n  - Sparkline (string)\n  - Activity (string)\nDiscovered:\
    \ 2026-04-30 11:26"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_dwh_sap.big_6_spend
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_dwh_sap
    databricks.com/table: big_6_spend
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_dwh_sap/big_6_spend
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
