apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-safex-safex-training-tracker
  title: bronze_non_sap_safex.safex_training_tracker
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap_safex.safex_training_tracker\n\
    Columns (23):\n  - Active (boolean)\n  - Complete (boolean)\n  - CompletionDate\
    \ (timestamp)\n  - Country (string)\n  - CourseCode (string)\n  - CourseTitle\
    \ (string)\n  - Delete (boolean)\n  - Department (string)\n  - DueDate (timestamp)\n\
    \  - EmployeeType (string)\n  - FirstName (string)\n  - Hours (float)\n  - Instance\
    \ (string)\n  - LastName (string)\n  - Organization (string)\n  ... +8 more\n\
    Discovered: 2026-04-30 11:39"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap_safex.safex_training_tracker
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap_safex
    databricks.com/table: safex_training_tracker
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap_safex/safex_training_tracker
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
