apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-aem-bkpf
  title: bronze_sap_aem.bkpf
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_aem.bkpf\n\
    Columns (183):\n  - MANDT (string)\n  - BUKRS (string)\n  - BELNR (string)\n \
    \ - GJAHR (int)\n  - BLART (string)\n  - BLDAT (date)\n  - BUDAT (date)\n  - MONAT\
    \ (string)\n  - CPUDT (date)\n  - CPUTM (string)\n  - AEDAT (date)\n  - UPDDT\
    \ (date)\n  - WWERT (date)\n  - USNAM (string)\n  - TCODE (string)\n  ... +168\
    \ more\nDiscovered: 2026-04-30 11:42"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - aem
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_aem.bkpf
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_aem
    databricks.com/table: bkpf
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_aem/bkpf
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
