apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-asp-j-1bbranch-slt
  title: bronze_sap_asp.j_1bbranch_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_asp.j_1bbranch_slt\n\
    Columns (72):\n  - DI_SEQUENCE_NUMBER (bigint)\n  - DI_OPERATION_TYPE (string)\n\
    \  - MANDT (string)\n  - BUKRS (string)\n  - BRANCH (string)\n  - BUPLA_TYPE (string)\n\
    \  - NAME (string)\n  - CGC_BRANCH (bigint)\n  - STATE_INSC (string)\n  - MUNIC_INSC\
    \ (string)\n  - INDUSTRY (string)\n  - SINGLE (string)\n  - ADRNR (string)\n \
    \ - NFDEC (bigint)\n  - KR_REPRES (string)\n  ... +57 more\nDiscovered: 2026-04-30\
    \ 11:51"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_asp.j_1bbranch_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_asp
    databricks.com/table: j_1bbranch_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_asp/j_1bbranch_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
