apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-safex-temp-safex-ptw-inventory-management
  title: bronze_non_sap_safex_temp.safex_ptw_inventory_management
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap_safex_temp.safex_ptw_inventory_management\n\
    Columns (26):\n  - AccessLocationDescription (string)\n  - Archive (boolean)\n\
    \  - Building (string)\n  - Column (string)\n  - Country (string)\n  - Department\
    \ (string)\n  - Floor (string)\n  - Instance (string)\n  - InventoryID (int)\n\
    \  - Inventory_Type (string)\n  - Inventory_Update_By (string)\n  - Inventory_Update_Date\
    \ (timestamp)\n  - MaintenanceReferenceID (string)\n  - Name (string)\n  - Organization\
    \ (string)\n  ... +11 more\nDiscovered: 2026-04-30 11:40"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap_safex_temp.safex_ptw_inventory_management
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap_safex_temp
    databricks.com/table: safex_ptw_inventory_management
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap_safex_temp/safex_ptw_inventory_management
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
