apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-p6-test-aiil-project-details
  title: bronze_p6_test.aiil_project_details
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_p6_test.aiil_project_details\n\
    Columns (10):\n  - ActivityDefaultActivityType (string)\n  - ActivityDefaultCalendarName\
    \ (string)\n  - ActivityDefaultCalendarObjectId (string)\n  - ActivityDefaultDurationType\
    \ (string)\n  - ActivityDefaultPercentCompleteType (string)\n  - Id (string)\n\
    \  - ObjectId (string)\n  - PrimaryResourcesCanMarkActivitiesAsCompleted (string)\n\
    \  - PrimaryResourcesCanUpdateActivityDates (string)\n  - __source_blob__ (string)\n\
    Discovered: 2026-04-30 11:41"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_p6_test.aiil_project_details
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_p6_test
    databricks.com/table: aiil_project_details
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_p6_test/aiil_project_details
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
