apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-ariba-new-rfp-overview-string
  title: bronze_ariba_new.rfp_overview_string
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_ariba_new.rfp_overview_string\n\
    Columns (58):\n  - Department_name (string)\n  - Department_uniqueName (string)\n\
    \  - acceptedSupplierAgreement (string)\n  - address_city (string)\n  - address_country\
    \ (string)\n  - address_postalcode (string)\n  - address_state (string)\n  - autoPublish\
    \ (string)\n  - availableExternalSystemIntegrationTypes (string)\n  - awardApprovalRequired\
    \ (string)\n  - baseLanguage (string)\n  - businessSystem_businessSystemId (string)\n\
    \  - businessSystem_businessSystemName (string)\n  - closeDate (string)\n  - createDate\
    \ (string)\n  ... +43 more\nDiscovered: 2026-04-30 11:25"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_ariba_new.rfp_overview_string
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_ariba_new
    databricks.com/table: rfp_overview_string
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_ariba_new/rfp_overview_string
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
