apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-kronos-krn-01-dbo-cmscontractor-wc
  title: bronze_kronos.krn_01_dbo_cmscontractor_wc
  description: 'Auto-discovered from Databricks Unity Catalog.

    Full name: adani_edl_governance_catalog_dev.bronze_kronos.krn_01_dbo_cmscontractor_wc

    Discovered: 2026-04-30 11:27'
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_kronos.krn_01_dbo_cmscontractor_wc
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_kronos
    databricks.com/table: krn_01_dbo_cmscontractor_wc
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_kronos/krn_01_dbo_cmscontractor_wc
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
