apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-ariba-auction-departments-custom-fields
  title: bronze_ariba.auction_departments_custom_fields
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_ariba.auction_departments_custom_fields\n\
    Columns (10):\n  - textValue (string)\n  - fieldDataType (string)\n  - fieldName\
    \ (string)\n  - fieldId (string)\n  - flexMasterDataTypeValue (string)\n  - TRANSFER_TIMESTAMP\
    \ (string)\n  - Department_uniqueName (string)\n  - Department_name (string)\n\
    \  - auction_id (string)\n  - LOADING_STATUS (string)\nDiscovered: 2026-04-30\
    \ 11:24"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_ariba.auction_departments_custom_fields
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_ariba
    databricks.com/table: auction_departments_custom_fields
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_ariba/auction_departments_custom_fields
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
