apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-safex-safex-im-events-data-string
  title: bronze_safex.safex_im_events_data_string
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_safex.safex_im_events_data_string\n\
    Columns (63):\n  - Building (string)\n  - Business (string)\n  - Closed_By (string)\n\
    \  - ClosureVerifiedDate (string)\n  - Core_Activity (string)\n  - Corrective_Action_and_Follow_Up\
    \ (string)\n  - Date_Recorded (string)\n  - Department (string)\n  - Description_and_Scope_of_Event\
    \ (string)\n  - Descriptive_Root_Cause (string)\n  - EventClosureDate (string)\n\
    \  - Event_Air_Ccode (string)\n  - Event_Air_Eunit (string)\n  - Event_Air_Exceedance\
    \ (string)\n  - Event_Air_Pcode (string)\n  ... +48 more\nDiscovered: 2026-04-30\
    \ 11:42"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_safex.safex_im_events_data_string
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_safex
    databricks.com/table: safex_im_events_data_string
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_safex/safex_im_events_data_string
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
