apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-p6-p6-project-issue
  title: bronze_non_sap_p6.p6_project_issue
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap_p6.p6_project_issue\n\
    Columns (23):\n  - CreateDate (string)\n  - CreateUser (string)\n  - DateIdentified\
    \ (string)\n  - IdentifiedBy (string)\n  - LastUpdateDate (string)\n  - LastUpdateUser\
    \ (string)\n  - Name (string)\n  - ObjectId (string)\n  - Priority (string)\n\
    \  - ProjectId (string)\n  - ProjectName (string)\n  - ProjectObjectId (string)\n\
    \  - Status (string)\n  - Notes (string)\n  - RawTextNote (string)\n  ... +8 more\n\
    Discovered: 2026-04-30 11:37"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap_p6.p6_project_issue
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap_p6
    databricks.com/table: p6_project_issue
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap_p6/p6_project_issue
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
