apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-aem-mssq-slt
  title: bronze_sap_aem.mssq_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_aem.mssq_slt\n\
    Columns (24):\n  - DI_SEQUENCE_NUMBER (bigint)\n  - DI_OPERATION_TYPE (string)\n\
    \  - MANDT (string)\n  - MATNR (string)\n  - WERKS (string)\n  - SOBKZ (string)\n\
    \  - PSPNR (string)\n  - LFGJA (string)\n  - LFMON (string)\n  - SQLAB (string)\n\
    \  - SQINS (string)\n  - SQSPE (string)\n  - SQEIN (string)\n  - ERSDA (date)\n\
    \  - KZBWS (string)\n  ... +9 more\nDiscovered: 2026-04-30 11:45"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - aem
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_aem.mssq_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_aem
    databricks.com/table: mssq_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_aem/mssq_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
