apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-btp-nfa-sub-approval
  title: bronze_btp.nfa_sub_approval
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_btp.nfa_sub_approval\n\
    Columns (43):\n  - StageApprovalDuration (string)\n  - ApprovalRequestArrivalDate\
    \ (string)\n  - SUMMARIZED_NEXTAPPROVEREMAILID (string)\n  - ID (string)\n  -\
    \ PROJECTID (string)\n  - PROJECTOWNER (string)\n  - EMAIL (string)\n  - VERSION\
    \ (string)\n  - EMPLOYEEID (string)\n  - NAME (string)\n  - TRANSFER_TIMESTAMP\
    \ (string)\n  - BU_NAME (string)\n  - ROLE (string)\n  - VERSIONNUMBER (string)\n\
    \  - CREATEDBY_1 (string)\n  ... +28 more\nDiscovered: 2026-04-30 11:26"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_btp.nfa_sub_approval
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_btp
    databricks.com/table: nfa_sub_approval
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_btp/nfa_sub_approval
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
