apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-ariba-ariba-rfp-logs
  title: bronze_non_sap_ariba.ariba_rfp_logs
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap_ariba.ariba_rfp_logs\n\
    Columns (19):\n  - source_blob (string)\n  - LOADING_STATUS (string)\n  - TRANSFER_TIMESTAMP\
    \ (string)\n  - action (string)\n  - dateCreated (string)\n  - details (string)\n\
    \  - effectiveUser_emailAddress (string)\n  - effectiveUser_name (string)\n  -\
    \ effectiveUser_uniqueName (string)\n  - logType (string)\n  - realUser_emailAddress\
    \ (string)\n  - realUser_name (string)\n  - realUser_uniqueName (string)\n  -\
    \ rfp_id (string)\n  - scope (string)\n  ... +4 more\nDiscovered: 2026-04-30 11:37"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap_ariba.ariba_rfp_logs
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap_ariba
    databricks.com/table: ariba_rfp_logs
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap_ariba/ariba_rfp_logs
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
