apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-safex-cm-contractor-employee-records
  title: bronze_non_sap.safex_cm_contractor_employee_records
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap.safex_cm_contractor_employee_records\n\
    Columns (14):\n  - Comments (string)\n  - ContactID (int)\n  - CourseGroup (string)\n\
    \  - CourseName (string)\n  - CourseTitle (string)\n  - DateofRecord (timestamp)\n\
    \  - EmployeeRecordID (int)\n  - ExpirationDateofRecord (timestamp)\n  - RecordedBy\
    \ (string)\n  - RecordedDate (timestamp)\n  - Scope (string)\n  - ScopeID (int)\n\
    \  - UpdateDate (timestamp)\n  - UpdatedBy (string)\nDiscovered: 2026-04-30 11:36"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap.safex_cm_contractor_employee_records
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap
    databricks.com/table: safex_cm_contractor_employee_records
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap/safex_cm_contractor_employee_records
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
