apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-mul-resb-slt
  title: bronze_sap_mul.resb_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_mul.resb_slt\n\
    Layer: bronze\nColumns (237):\n  - DI_SEQUENCE_NUMBER (bigint)\n  - DI_OPERATION_TYPE\
    \ (string)\n  - MANDT (string)\n  - RSNUM (string)\n  - RSPOS (string)\n  - RSART\
    \ (string)\n  - BDART (string)\n  - RSSTA (string)\n  - XLOEK (string)\n  - XWAOK\
    \ (string)\n  - KZEAR (string)\n  - XFEHL (string)\n  - MATNR (string)\n  - WERKS\
    \ (string)\n  - LGORT (string)\n  - PRVBE (string)\n  - CHARG (string)\n  - PLPLA\
    \ (string)\n  - SOBKZ (string)\n  - BDTER (date)\n  ... +217 more\nDiscovered:\
    \ 2026-04-30 12:21"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - mul
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_mul.resb_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_mul
    databricks.com/table: resb_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_mul/resb_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
