apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-asp-knvi-slt
  title: bronze_sap_asp.knvi_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_asp.knvi_slt\n\
    Columns (13):\n  - DI_SEQUENCE_NUMBER (bigint)\n  - DI_OPERATION_TYPE (string)\n\
    \  - MANDT (string)\n  - KUNNR (string)\n  - ALAND (string)\n  - TATYP (string)\n\
    \  - TAXKD (string)\n  - ODQ_CHANGEMODE (string)\n  - ODQ_ENTITYCNTR (string)\n\
    \  - DI_TIMESTAMP (timestamp)\n  - SYS_INGESTION_DATE (date)\n  - SYS_FILE_NAME\
    \ (string)\n  - SYS_MODIFIED_TIME (timestamp)\nDiscovered: 2026-04-30 11:51"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_asp.knvi_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_asp
    databricks.com/table: knvi_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_asp/knvi_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
