apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-alp-prps
  title: bronze_sap_alp.prps
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_alp.prps\n\
    Columns (128):\n  - MANDT (string)\n  - PSPNR (string)\n  - POSID (string)\n \
    \ - POST1 (string)\n  - OBJNR (string)\n  - PSPHI (string)\n  - POSKI (string)\n\
    \  - ERNAM (string)\n  - ERDAT (date)\n  - AENAM (string)\n  - AEDAT (date)\n\
    \  - VERNR (string)\n  - VERNA (string)\n  - ASTNR (string)\n  - ASTNA (string)\n\
    \  ... +113 more\nDiscovered: 2026-04-30 11:49"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_alp.prps
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_alp
    databricks.com/table: prps
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_alp/prps
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
