apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-p6-p6-activity
  title: bronze_non_sap_p6.p6_activity
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap_p6.p6_activity\n\
    Columns (31):\n  - Baseline1FinishDate (string)\n  - Baseline1StartDate (string)\n\
    \  - BaselineDuration (string)\n  - BaselineFinishDate (string)\n  - BaselineStartDate\
    \ (string)\n  - DataDate (string)\n  - FinishDate (string)\n  - IsCritical (string)\n\
    \  - IsLongestPath (string)\n  - Name (string)\n  - ObjectId (string)\n  - PerformancePercentComplete\
    \ (string)\n  - ProjectId (string)\n  - ProjectName (string)\n  - ProjectObjectId\
    \ (string)\n  ... +16 more\nDiscovered: 2026-04-30 11:37"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap_p6.p6_activity
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap_p6
    databricks.com/table: p6_activity
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap_p6/p6_activity
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
