apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-mul-user-addr
  title: bronze_sap_mul.user_addr
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_mul.user_addr\n\
    Layer: bronze\nColumns (24):\n  - MANDT (string)\n  - BNAME (string)\n  - NAME_FIRST\
    \ (string)\n  - NAME_LAST (string)\n  - NAME_TEXTC (string)\n  - TEL_EXTENS (string)\n\
    \  - KOSTL (string)\n  - BUILDING (string)\n  - ROOMNUMBER (string)\n  - DEPARTMENT\
    \ (string)\n  - INHOUSE_ML (string)\n  - NAME1 (string)\n  - CITY1 (string)\n\
    \  - POST_CODE1 (string)\n  - MC_NAMEFIR (string)\n  - MC_NAMELAS (string)\n \
    \ - MC_NAME1 (string)\n  - MC_CITY1 (string)\n  - COMPANY (string)\n  - IDADTYPE\
    \ (string)\n  ... +4 more\nDiscovered: 2026-04-30 12:22"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - mul
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_mul.user_addr
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_mul
    databricks.com/table: user_addr
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_mul/user_addr
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
