apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-asp-regup-slt
  title: bronze_sap_asp.regup_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_asp.regup_slt\n\
    Columns (199):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data Services-generated integer\
    \ for sequencing\n  - DI_OPERATION_TYPE (string) -- Data Services-generated row\
    \ operation type\n  - MANDT (string) -- Client\n  - LAUFD (date) -- Run Date\n\
    \  - LAUFI (string) -- Identification\n  - XVORL (string) -- XVORL\n  - ZBUKR\
    \ (string) -- Paying company code\n  - LIFNR (string) -- Vendor\n  - KUNNR (string)\
    \ -- Customer\n  - EMPFG (string) -- Payment recipient\n  - VBLNR (string) --\
    \ Payment document no.\n  - BUKRS (string) -- Company Code\n  - BELNR (string)\
    \ -- Document Number\n  - GJAHR (bigint) -- Fiscal Year\n  - BUZEI (bigint) --\
    \ Line item\n  ... +184 more\nDiscovered: 2026-04-30 11:53"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_asp.regup_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_asp
    databricks.com/table: regup_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_asp/regup_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
