apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-safex-temp-safex-im-hours-logged
  title: bronze_non_sap_safex_temp.safex_im_hours_logged
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap_safex_temp.safex_im_hours_logged\n\
    Columns (45):\n  - Acrive (int)\n  - Archive (boolean)\n  - Business (string)\n\
    \  - Comments (string)\n  - HS_Dafw (float)\n  - HS_Drwa (float)\n  - HS_Hours\
    \ (float)\n  - HS_Ill_Dafw (float)\n  - HS_Ill_Drwa (float)\n  - HS_Num_Dafw (int)\n\
    \  - HS_Num_Dafw_Rwa (int)\n  - HS_Num_Fatality (int)\n  - HS_Num_Ill_Dafw (int)\n\
    \  - HS_Num_Ill_Dafw_Rwa (int)\n  - HS_Num_Ill_Dust (int)\n  ... +30 more\nDiscovered:\
    \ 2026-04-30 11:39"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap_safex_temp.safex_im_hours_logged
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap_safex_temp
    databricks.com/table: safex_im_hours_logged
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap_safex_temp/safex_im_hours_logged
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
