apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-aem-ss-bsak
  title: bronze_sap_aem_ss.bsak
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_aem_ss.bsak\n\
    Columns (187):\n  - MANDT (string)\n  - BUKRS (string)\n  - LIFNR (string)\n \
    \ - UMSKS (string)\n  - UMSKZ (string)\n  - AUGDT (timestamp)\n  - AUGBL (string)\n\
    \  - ZUONR (string)\n  - GJAHR (string)\n  - BELNR (string)\n  - BUZEI (string)\n\
    \  - BUDAT (timestamp)\n  - BLDAT (timestamp)\n  - CPUDT (timestamp)\n  - WAERS\
    \ (string)\n  ... +172 more\nDiscovered: 2026-04-30 11:48"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - aem
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_aem_ss.bsak
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_aem_ss
    databricks.com/table: bsak
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_aem_ss/bsak
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
