apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-safex-safex-cm-contractor-actions
  title: bronze_safex.safex_cm_contractor_actions
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_safex.safex_cm_contractor_actions\n\
    Columns (28):\n  - ActionDate (timestamp)\n  - ActionID (int)\n  - ActionLocation\
    \ (string)\n  - ActionType (string)\n  - ActivateID (int)\n  - AssignedTo (double)\n\
    \  - CCList (string)\n  - Category (string)\n  - CloseDate (timestamp)\n  - ClosureComments\
    \ (string)\n  - ClosureDueDate (timestamp)\n  - CorrectiveAction (string)\n  -\
    \ ExternalSubmit (boolean)\n  - FOMID (int)\n  - FirmID (int)\n  ... +13 more\n\
    Discovered: 2026-04-30 11:41"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_safex.safex_cm_contractor_actions
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_safex
    databricks.com/table: safex_cm_contractor_actions
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_safex/safex_cm_contractor_actions
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
