apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-ariba-v3-e-auction-bid-console-combined
  title: bronze_ariba.v3_e_auction_bid_console_combined
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_ariba.v3_e_auction_bid_console_combined\n\
    Columns (85):\n  - value_supplierValue_currency (string)\n  - value_supplierValue_amount\
    \ (string)\n  - rollup (string)\n  - itemsWithBid (string)\n  - item_terms_value_supplierValue_currency\
    \ (string)\n  - item_terms_value_supplierValue_amount (string)\n  - item_terms_value_moneyValue_currency\
    \ (string)\n  - item_terms_value_moneyValue_amount (string)\n  - item_terms_valueTypeName\
    \ (string)\n  - item_terms_title (string)\n  - item_terms_rollup (string)\n  -\
    \ item_terms_rankOrder (string)\n  - item_terms_prerequisiteReviewStatus (string)\n\
    \  - item_terms_itemBiddingRules_trafficLightBidRule_ruleEnabled (string)\n  -\
    \ item_terms_itemBiddingRules_trafficLightBidRule_rankPosition (string)\n  ...\
    \ +70 more\nDiscovered: 2026-04-30 11:25"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_ariba.v3_e_auction_bid_console_combined
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_ariba
    databricks.com/table: v3_e_auction_bid_console_combined
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_ariba/v3_e_auction_bid_console_combined
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
