apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-alp-ska1
  title: bronze_sap_alp.ska1
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_alp.ska1\n\
    Columns (25):\n  - MANDT (string)\n  - KTOPL (string)\n  - SAKNR (string)\n  -\
    \ XBILK (string)\n  - SAKAN (string)\n  - BILKT (string)\n  - ERDAT (date)\n \
    \ - ERNAM (string)\n  - GVTYP (string)\n  - KTOKS (string)\n  - MUSTR (string)\n\
    \  - VBUND (string)\n  - XLOEV (string)\n  - XSPEA (string)\n  - XSPEB (string)\n\
    \  ... +10 more\nDiscovered: 2026-04-30 11:49"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_alp.ska1
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_alp
    databricks.com/table: ska1
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_alp/ska1
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
