apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-ariba-new-auction-template
  title: bronze_ariba_new.auction_template
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_ariba_new.auction_template\n\
    Columns (14):\n  - title (string)\n  - internalId (string)\n  - currency (string)\n\
    \  - status (string)\n  - eventTypeName (string)\n  - owner_name (string)\n  -\
    \ owner_uniqueName (string)\n  - auction_id (string)\n  - createDate (string)\n\
    \  - hasAward (string)\n  - parentProjectId (string)\n  - eventStateName (string)\n\
    \  - TRANSFER_TIMESTAMP (string)\n  - LOADING_STATUS (string)\nDiscovered: 2026-04-30\
    \ 11:25"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_ariba_new.auction_template
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_ariba_new
    databricks.com/table: auction_template
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_ariba_new/auction_template
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
