apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-dwh-sap-service-master-load
  title: bronze_dwh_sap.service_master_load
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_dwh_sap.service_master_load\n\
    Columns (16):\n  - Inst (string)\n  - Service_Code (string)\n  - Service_Code_Text\
    \ (string)\n  - Created_On (timestamp)\n  - Serv_Cat (string)\n  - Serv_Cat_Text\
    \ (string)\n  - Serv_Group (string)\n  - Serv_Group_Text (string)\n  - UoM (string)\n\
    \  - UoM_Text (string)\n  - ValCl (string)\n  - ValCl_Text (string)\n  - Tax_Tariff_Code\
    \ (string)\n  - Tax_Ind (string)\n  - PS (string)\n  ... +1 more\nDiscovered:\
    \ 2026-04-30 11:27"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_dwh_sap.service_master_load
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_dwh_sap
    databricks.com/table: service_master_load
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_dwh_sap/service_master_load
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
