apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-alp-mara
  title: bronze_sap_alp.mara
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_alp.mara\n\
    Columns (282):\n  - MANDT (string)\n  - MATNR (string)\n  - ERSDA (date)\n  -\
    \ CREATED_AT_TIME (string)\n  - ERNAM (string)\n  - LAEDA (date)\n  - AENAM (string)\n\
    \  - VPSTA (string)\n  - PSTAT (string)\n  - LVORM (string)\n  - MTART (string)\n\
    \  - MBRSH (string)\n  - MATKL (string)\n  - BISMT (string)\n  - MEINS (string)\n\
    \  ... +267 more\nDiscovered: 2026-04-30 11:49"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_alp.mara
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_alp
    databricks.com/table: mara
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_alp/mara
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
