apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-manual-files-directtax-transmission-clause-18-addition-f
  title: bronze_manual_files.directtax_transmission_clause_18_addition_fsd_inputs_file
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_manual_files.directtax_transmission_clause_18_addition_fsd_inputs_file\n\
    Columns (6):\n  - age_rate_of_depreciation (string)\n  - asset_class_code (string)\n\
    \  - companies_act (string)\n  - fiscal_year (string)\n  - income_tax_block (string)\n\
    \  - slm_or_wdv (string)\nDiscovered: 2026-04-30 11:33"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_manual_files.directtax_transmission_clause_18_addition_fsd_inputs_file
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_manual_files
    databricks.com/table: directtax_transmission_clause_18_addition_fsd_inputs_file
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_manual_files/directtax_transmission_clause_18_addition_fsd_inputs_file
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
