apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-asp-mdkp-slt
  title: bronze_sap_asp.mdkp_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_asp.mdkp_slt\n\
    Columns (106):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data Services-generated integer\
    \ for sequencing\n  - DI_OPERATION_TYPE (string) -- Data Services-generated row\
    \ operation type\n  - MANDT (string) -- Client\n  - DTART (string) -- MRP list\
    \ type\n  - MATNR (string) -- Material\n  - PLWRK (string) -- Plant\n  - PLSCN\
    \ (bigint) -- Planning Scenario\n  - DTNUM (bigint) -- No. MRP table\n  - DSDAT\
    \ (date) -- MRP date\n  - BDBKZ (string) -- Processed MRP lists\n  - SLKZ1 (string)\
    \ -- Exception\n  - SLKZ2 (string) -- Exception\n  - SLKZ3 (string) -- Exception\n\
    \  - SLKZ4 (string) -- Exception\n  - SLKZ5 (string) -- Exception\n  ... +91 more\n\
    Discovered: 2026-04-30 11:52"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_asp.mdkp_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_asp
    databricks.com/table: mdkp_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_asp/mdkp_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
