apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-gentec-gen-02-mundra-genetec-punchdata
  title: bronze_gentec.gen_02_mundra_genetec_punchdata
  description: 'Auto-discovered from Databricks Unity Catalog.

    Full name: adani_edl_governance_catalog_dev.bronze_gentec.gen_02_mundra_genetec_punchdata

    Discovered: 2026-04-30 11:27'
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_gentec.gen_02_mundra_genetec_punchdata
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_gentec
    databricks.com/table: gen_02_mundra_genetec_punchdata
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_gentec/gen_02_mundra_genetec_punchdata
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
