apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-tpdd-tpdd
  title: bronze_non_sap_tpdd.tpdd
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap_tpdd.tpdd\n\
    Columns (528):\n  - agency_signature_agency_address (string)\n  - agency_signature_agency_contact\
    \ (string)\n  - agency_signature_agency_email (string)\n  - agency_signature_agency_gst\
    \ (string)\n  - agency_signature_agency_name (string)\n  - agency_signature_agency_website\
    \ (string)\n  - agency_signature_disclaimer (string)\n  - message (string)\n \
    \ - results_AML_and_PEP_Check_additional_details_aml_pep (string)\n  - results_AML_and_PEP_Check_enforcement_list\
    \ (string)\n  - results_AML_and_PEP_Check_sanction_list (string)\n  - results_AML_and_PEP_Check_adverse_media\
    \ (string)\n  - results_AML_and_PEP_Check_pep_list (string)\n  - results_AML_and_PEP_Check_watch_list\
    \ (string)\n  - results_Auditor_Observation_Domestic_auditor_observation (string)\n\
    \  ... +513 more\nDiscovered: 2026-04-30 11:40"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap_tpdd.tpdd
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap_tpdd
    databricks.com/table: tpdd
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap_tpdd/tpdd
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
