apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-mul-eban-slt
  title: bronze_sap_mul.eban_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_mul.eban_slt\n\
    Layer: bronze\nColumns (285):\n  - DI_SEQUENCE_NUMBER (bigint)\n  - DI_OPERATION_TYPE\
    \ (string)\n  - MANDT (string)\n  - BANFN (string)\n  - BNFPO (bigint)\n  - BSART\
    \ (string)\n  - BSTYP (string)\n  - BSAKZ (string)\n  - LOEKZ (string)\n  - STATU\
    \ (string)\n  - ESTKZ (string)\n  - FRGKZ (string)\n  - FRGZU (string)\n  - FRGST\
    \ (string)\n  - EKGRP (string)\n  - ERNAM (string)\n  - ERDAT (date)\n  - AFNAM\
    \ (string)\n  - TXZ01 (string)\n  - MATNR (string)\n  ... +265 more\nDiscovered:\
    \ 2026-04-30 12:19"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - mul
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_mul.eban_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_mul
    databricks.com/table: eban_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_mul/eban_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
