apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-lms-percipio-learning-activity
  title: bronze_lms.percipio_learning_activity
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_lms.percipio_learning_activity\n\
    Columns (47):\n  - userId (string)\n  - firstName (string)\n  - lastName (string)\n\
    \  - audience (string)\n  - contentUuid (string)\n  - contentId (string)\n  -\
    \ contentTitle (string)\n  - contentType (string)\n  - languageCode (string)\n\
    \  - source (string)\n  - status (string)\n  - completedDate (string)\n  - badgeEarned\
    \ (string)\n  - duration (string)\n  - estimatedDuration (string)\n  ... +32 more\n\
    Discovered: 2026-04-30 11:28"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_lms.percipio_learning_activity
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_lms
    databricks.com/table: percipio_learning_activity
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_lms/percipio_learning_activity
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
