apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-ariba-rfp-rfq-refrence
  title: bronze_ariba.rfp_rfq_refrence
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_ariba.rfp_rfq_refrence\n\
    Columns (2):\n  - tablename (string)\n  - max_transfer_timestamp (string)\nDiscovered:\
    \ 2026-04-30 11:24"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_ariba.rfp_rfq_refrence
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_ariba
    databricks.com/table: rfp_rfq_refrence
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_ariba/rfp_rfq_refrence
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
