apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-mul-cdpos-slt
  title: bronze_sap_mul.cdpos_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_mul.cdpos_slt\n\
    Layer: bronze\nColumns (24):\n  - DI_SEQUENCE_NUMBER (bigint)\n  - DI_OPERATION_TYPE\
    \ (string)\n  - MANDANT (string)\n  - OBJECTCLAS (string)\n  - OBJECTID (string)\n\
    \  - CHANGENR (string)\n  - TABNAME (string)\n  - TABKEY (string)\n  - FNAME (string)\n\
    \  - CHNGIND (string)\n  - TEXT_CASE (string)\n  - UNIT_OLD (string)\n  - UNIT_NEW\
    \ (string)\n  - CUKY_OLD (string)\n  - CUKY_NEW (string)\n  - VALUE_NEW (string)\n\
    \  - VALUE_OLD (string)\n  - _DATAAGING (date)\n  - SYS_INGESTION_DATE (date)\n\
    \  - SYS_FILE_NAME (string)\n  ... +4 more\nDiscovered: 2026-04-30 12:19"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - mul
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_mul.cdpos_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_mul
    databricks.com/table: cdpos_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_mul/cdpos_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
