apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-mul-zfibpt11001-slt
  title: bronze_sap_mul.zfibpt11001_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_mul.zfibpt11001_slt\n\
    Layer: bronze\nColumns (161):\n  - DI_SEQUENCE_NUMBER (bigint)\n  - DI_OPERATION_TYPE\
    \ (string)\n  - MANDT (string)\n  - BUKRS (string)\n  - CHK_KEY (string)\n  -\
    \ CHK_DOC_TYP (bigint)\n  - GJAHR (bigint)\n  - DOC_NO (string)\n  - EBELP (bigint)\n\
    \  - KSCHL (string)\n  - BUZEI (bigint)\n  - DOC_SUB_CAT (bigint)\n  - SHKZG (string)\n\
    \  - CFPAYGUID (string)\n  - DBPERIOD (date)\n  - DEPERIOD (date)\n  - CHK_FIS_YR\
    \ (bigint)\n  - CHK_CR_DAT (date)\n  - CHK_CR_TM (string)\n  - CHK_CR_USR (string)\n\
    \  ... +141 more\nDiscovered: 2026-04-30 12:23"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - mul
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_mul.zfibpt11001_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_mul
    databricks.com/table: zfibpt11001_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_mul/zfibpt11001_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
