apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-sap-aem-crca-slt
  title: bronze_sap_aem.crca_slt
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_sap_aem.crca_slt\n\
    Columns (35):\n  - DI_SEQUENCE_NUMBER (bigint) -- Data Services-generated integer\
    \ for sequencing\n  - DI_OPERATION_TYPE (string) -- Data Services-generated row\
    \ operation type\n  - MANDT (string) -- Client\n  - OBJTY (string) -- Object Type\n\
    \  - OBJID (bigint) -- Object ID\n  - CANUM (bigint) -- Work center cap. no.\n\
    \  - BEGDA (date) -- Start date\n  - ENDDA (date) -- End Date\n  - AEDAT_KAPA\
    \ (date) -- Changed on\n  - AENAM_KAPA (string) -- User Name\n  - KAPID (bigint)\
    \ -- Capacity ID\n  - FORK1 (string) -- Setup formula\n  - FORK2 (string) -- Processing\
    \ formula\n  - FORK3 (string) -- Teardown formula\n  - FORKN (string) -- Other\
    \ formula\n  ... +20 more\nDiscovered: 2026-04-30 11:43"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  - aem
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_sap_aem.crca_slt
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_sap_aem
    databricks.com/table: crca_slt
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_sap_aem/crca_slt
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
