apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-manual-files-directtax-thermal-clause-40-turnover-manual
  title: bronze_manual_files.directtax_thermal_clause_40_turnover_manual_file
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_manual_files.directtax_thermal_clause_40_turnover_manual_file\n\
    Columns (3):\n  - fiscal_year (string)\n  - gl_code (string)\n  - particulars\
    \ (string)\nDiscovered: 2026-04-30 11:33"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_manual_files.directtax_thermal_clause_40_turnover_manual_file
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_manual_files
    databricks.com/table: directtax_thermal_clause_40_turnover_manual_file
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_manual_files/directtax_thermal_clause_40_turnover_manual_file
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
