apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-non-sap-safex-cm-active-site-contractor-firms
  title: bronze_non_sap.safex_cm_active_site_contractor_firms
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_non_sap.safex_cm_active_site_contractor_firms\n\
    Columns (25):\n  - ActivateID (int)\n  - Business (string)\n  - CertificateOfInsuranceExpirationDate\
    \ (timestamp)\n  - CompanyName (string)\n  - ContactName (string)\n  - ContractorArchive\
    \ (boolean)\n  - ContractorType (string)\n  - Department (string)\n  - EndDate\
    \ (timestamp)\n  - FirmCountry (string)\n  - FirmID (int)\n  - OnSiteWorkSupervisionRequired\
    \ (string)\n  - ParentFirmID (double)\n  - ProjectSafetyPlanReceived (string)\n\
    \  - ProjectTitle (string)\n  ... +10 more\nDiscovered: 2026-04-30 11:36"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_non_sap.safex_cm_active_site_contractor_firms
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_non_sap
    databricks.com/table: safex_cm_active_site_contractor_firms
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_non_sap/safex_cm_active_site_contractor_firms
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
