apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bronze-dwh-sap-bank-accounts
  title: bronze_dwh_sap.bank_accounts
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.bronze_dwh_sap.bank_accounts\n\
    Columns (15):\n  - Server (string)\n  - BU (string)\n  - Co_Code (string)\n  -\
    \ Company_Name (string)\n  - GL_Account (string)\n  - Long_Text (string)\n  -\
    \ Account_Number (string)\n  - House_Bk (string)\n  - IFSC_Code (string)\n  -\
    \ Bank_Name (string)\n  - City (string)\n  - Crcy (string)\n  - Amount (double)\n\
    \  - Last_Trxn_Dt (string)\n  - GL_Status (string)\nDiscovered: 2026-04-30 11:26"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - bronze
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.bronze_dwh_sap.bank_accounts
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: bronze_dwh_sap
    databricks.com/table: bank_accounts
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/bronze_dwh_sap/bank_accounts
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
