apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-equipment-malfunction
  title: silver.equipment_malfunction
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver.equipment_malfunction\n\
    Layer: silver\nColumns (22):\n  - notification_no (string)\n  - planning_plant\
    \ (string)\n  - location_acc_assignment (string)\n  - equipment_id (string)\n\
    \  - breakdown_ind (string)\n  - malfunction_start_date (date)\n  - malfunction_end_date\
    \ (date)\n  - equipment_affected (string)\n  - technical_inspection_date (date)\n\
    \  - maintenance_plan (string)\n  - client_id (string) -- It is a three-char alphanumeric\
    \ identifier that represents a client in the SAP system. A client is the highest\
    \ organizational unit in SAP and serves as a self-contained unit with its own\
    \ master data and set of tables\n  - hash_key (string) -- System-generated hash\
    \ key used for uniquely identifying records and ensuring data integrity.\n  -\
    \ identifier (string) -- Custom discriminator to differentiate vendors across\
    \ multiple SAP instances when client code alone is insufficient.\n  - is_active\
    \ (string) -- Flag indicating whether the record is currently active. Y indicates\
    \ an active record which means that it is the latest record N indicates an in-active\
    \ record which means that this record is old and has been changed.\n  - sys_effective_start_date\
    \ (date)\n  - sys_effective_end_date (date)\n  - breakdown_duration (double)\n\
    \  - functional_location_affected (string)\n  - effect_on_operation (string)\n\
    \  - technical_inspection_by (string)\n  ... +2 more\nDiscovered: 2026-04-30 12:30"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver.equipment_malfunction
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver
    databricks.com/table: equipment_malfunction
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver/equipment_malfunction
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
  dependsOn:
  - component:silver-sap-cleansed-equi-mstr
