apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-notification-activity
  title: silver.notification_activity
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver.notification_activity\n\
    Layer: silver\nColumns (19):\n  - client_id (string)\n  - notification_no (string)\n\
    \  - activity_code_grp (string)\n  - activity_code (string)\n  - activity_code_catalog\
    \ (string)\n  - version_number (string)\n  - created_by (string)\n  - created_on\
    \ (date)\n  - planned_activity_start_date (date)\n  - planned_activity_end_date\
    \ (date)\n  - activity_text (string)\n  - identifier (string)\n  - hash_key (string)\
    \ -- System-generated hash key used for uniquely identifying records and ensuring\
    \ data integrity.\n  - is_active (string) -- Flag indicating whether the record\
    \ is currently active. Y indicates an active record which means that it is the\
    \ latest record N indicates an in-active record which means that this record is\
    \ old and has been changed.\n  - sys_effective_start_date (date)\n  - sys_effective_end_date\
    \ (date)\n  - activity_no (bigint)\n  - notification_item (bigint)\n  - quantity_factor\
    \ (bigint)\nDiscovered: 2026-04-30 12:31"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver.notification_activity
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver
    databricks.com/table: notification_activity
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver/notification_activity
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
