apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-taxcode
  title: silver.taxcode
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver.taxcode\n\
    Layer: silver\nColumns (10):\n  - client_id (string) -- It is a three-char alphanumeric\
    \ identifier that represents a client in the SAP system. A client is the highest\
    \ organizational unit in SAP and serves as a self-contained unit with its own\
    \ master data and set of tables.\n  - tax_procedure (string) -- Tax Calculation\
    \ Procedure – determines how taxes are calculated. Examples: -TAXINJ indicates\
    \ Sales Tax India -TAXINN indicates IN; India taxes new\n  - tax_code (string)\
    \ -- Specifies the tax code used for calculating input/output tax. Determines\
    \ how tax is calculated and posted for the transaction. Examples: 1 indicates\
    \ GST Domestic Sales -Output. 2 indicates GST : Customer Adv (Intra State) 18%.\
    \ A indicates GST Domestic Supply-Cenvatable\n  - identifier (string) -- Custom\
    \ discriminator to differentiate vendors across multiple SAP instances when client\
    \ code alone is insufficient.\n  - tax_type (string) -- This field indicates whether\
    \ a tax is treated as an input tax or an output tax. It helps the to understand\
    \ which side of a transaction the tax applies to, ensuring the correct direction\
    \ of tax handling. Common Values: A is for Output Tax. V is for Input tax\n  -\
    \ tax_code_desc (string) -- Description of the Tax Code – e.g., Output Tax 18%,\
    \ Input Tax 5%\n  - sys_effective_start_date (date) -- System Effective Start\
    \ Date, indicating when the record became valid in the system.\n  - sys_effective_end_date\
    \ (date) -- System Effective End Date, indicating when the record ceased to be\
    \ valid in the system.\n  - is_active (string) -- Flag indicating whether the\
    \ record is currently active. Y indicates an active record which means that it\
    \ is the latest record N indicates an in-active record which means that this record\
    \ is old and has been changed\n  - hash_key (string) -- System-generated hash\
    \ key used for uniquely identifying records and ensuring data integrity.\nDiscovered:\
    \ 2026-04-30 12:32"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver.taxcode
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver
    databricks.com/table: taxcode
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver/taxcode
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
