apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-controlling-area
  title: silver.controlling_area
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver.controlling_area\n\
    Layer: silver\nColumns (10):\n  - client_id (string) -- It is a three-char alphanumeric\
    \ identifier that represents a client in the SAP system. A client is the highest\
    \ organizational unit in SAP and serves as a self-contained unit with its own\
    \ master data and set of tables.\n  - controlling_area (string) -- It defines\
    \ the highest organizational unit in Controlling (CO) and groups company codes\
    \ for cost accounting purposes. Examples: 1000- Adani Infrastructure Grp\n  -\
    \ currency_key (string) -- It is a standard field that represents the currency\
    \ key used. It defines the currency in which amounts are recorded, such as INR,\
    \ USD, or EUR. This field ensures consistency in financial reporting, pricing,\
    \ and accounting\n  - chart_of_accounts (string) -- Defines the structure and\
    \ categorization of G/L accounts assigned to a company code. Enables standardized\
    \ financial reporting and supports legal and management reporting requirements.\
    \ \n⦁ Max length 4 char\n  - controlling_area_desc (string) -- This field represents\
    \ the textual description of the controlling area, providing clarity on its business\
    \ scope and purpose.\n  - identifier (string) -- Custom discriminator to differentiate\
    \ vendors across multiple SAP instances when client code alone is insufficient.\n\
    \  - hash_key (string) -- System-generated hash key used for uniquely identifying\
    \ records and ensuring data integrity.\n  - is_active (string) -- Flag indicating\
    \ whether the record is currently active. Y indicates an active record which means\
    \ that it is the latest record N indicates an in-active record which means that\
    \ this record is old and has been changed\n  - sys_effective_start_date (date)\
    \ -- System Effective Start Date, indicating when the record became valid in the\
    \ system.\n  - sys_effective_end_date (date) -- System Effective End Date, indicating\
    \ when the record ceased to be valid in the system.\nDiscovered: 2026-04-30 12:30"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver.controlling_area
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver
    databricks.com/table: controlling_area
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver/controlling_area
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
