apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: silver-functional-location
  title: silver.functional_location
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.silver.functional_location\n\
    Layer: silver\nColumns (15):\n  - client_id (string)\n  - functional_location_id\
    \ (int)\n  - created_on (date)\n  - planning_plant (string)\n  - superor_func_loc\
    \ (string)\n  - work_centre_object_id (int)\n  - location_acc_assignment (string)\n\
    \  - maintenance_plant (string)\n  - business_area (string)\n  - company_code\
    \ (string)\n  - identifier (string)\n  - hash_key (string) -- System-generated\
    \ hash key used for uniquely identifying records and ensuring data integrity.\n\
    \  - is_active (string) -- Flag indicating whether the record is currently active.\
    \ Y indicates an active record which means that it is the latest record N indicates\
    \ an in-active record which means that this record is old and has been changed.\n\
    \  - sys_effective_start_date (date)\n  - sys_effective_end_date (date)\nDiscovered:\
    \ 2026-04-30 12:30"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - silver
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.silver.functional_location
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: silver
    databricks.com/table: functional_location
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/silver/functional_location
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
