apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: access-control-pipelines
  title: access_control.pipelines
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.access_control.pipelines\n\
    Columns (12):\n  - workspace_id (string) -- The ID of the workspace this pipeline\
    \ belongs to.\n  - pipeline_id (string) -- The ID of the pipeline.\n  - pipeline_type\
    \ (string) -- The type of pipeline.\n  - name (string) -- The user-supplied name\
    \ of the pipeline.\n  - created_by (string) -- The email/ID of the service principal\
    \ who created the pipeline.\n  - run_as (string) -- The email/ID of the service\
    \ principal whose permissions are used for the pipeline run.\n  - tags (map<string,string>)\
    \ -- The user-supplied tags associated with the pipeline.\n  - settings (struct<photon:boolean,development:boolean,continuous:boolean,serverless:boolean,edition:string,channel:string>)\
    \ -- The settings of the pipeline.\n  - configuration (map<string,string>) --\
    \ The user-supplied configuration of the pipeline.\n  - change_time (timestamp)\
    \ -- The time when the pipeline was last modified. Timezone recorded as +00:00\
    \ (UTC).\n  - delete_time (timestamp) -- The time when a pipeline was deleted\
    \ by the user. Timezone recorded as +00:00 (UTC).\n  - account_id (string) --\
    \ The ID of the account this pipeline belongs to.\nDiscovered: 2026-04-30 11:11"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.access_control.pipelines
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: access_control
    databricks.com/table: pipelines
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/access_control/pipelines
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
