apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: access-control-jobs
  title: access_control.jobs
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.access_control.jobs\n\
    Columns (10):\n  - account_id (string) -- The ID of the account this job belongs\
    \ to.\n  - workspace_id (string) -- The ID of the workspace this job belongs to.\n\
    \  - job_id (string) -- The ID of the job. Only unique within a single workspace.\n\
    \  - name (string) -- The user-supplied name of the job.\n  - creator_id (string)\
    \ -- The ID of the principal who created the job.\n  - tags (map<string,string>)\
    \ -- The user-supplied custom tags associated with this job.\n  - run_as (string)\
    \ -- The ID of the user or service principal whose permissions are used for the\
    \ job run.\n  - change_time (timestamp) -- The time when the job was last modified.\
    \ Timezone recorded as +00:00 (UTC).\n  - delete_time (timestamp) -- The time\
    \ when the job was deleted by the user. Timezone recorded as +00:00 (UTC).\n \
    \ - description (string) -- The user-supplied description of the job. **Not populated\
    \ for rows emitted before late August 2024.**\nDiscovered: 2026-04-30 11:11"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.access_control.jobs
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: access_control
    databricks.com/table: jobs
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/access_control/jobs
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
