apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: access-control-job-task-run-timeline
  title: access_control.job_task_run_timeline
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.access_control.job_task_run_timeline\n\
    Columns (12):\n  - account_id (string) -- The ID of the account this job belongs\
    \ to.\n  - workspace_id (string) -- The ID of the workspace this job belongs to.\n\
    \  - job_id (string) -- The ID of the job. Only unique within a single workspace.\n\
    \  - run_id (string) -- The ID of the task run.\n  - period_start_time (timestamp)\
    \ -- The start time for the task or for the time period. Timezone information\
    \ is recorded at the end of the value with +00:00 representing UTC.\n  - period_end_time\
    \ (timestamp) -- The end time for the task or for the time period. Timezone information\
    \ is recorded at the end of the value with +00:00 representing UTC.\n  - task_key\
    \ (string) -- The reference key for a task in a job. This key is only unique within\
    \ a single job.\n  - compute_ids (array<string>) -- An array containing the IDs\
    \ of compute used by the job task.\n  - result_state (string) -- The outcome of\
    \ the job task run.\n  - job_run_id (string) -- The ID of the job run. **Not populated\
    \ for rows emitted before late August 2024.**\n  - parent_run_id (string) -- The\
    \ ID of the parent run. **Not populated for rows emitted before late August 2024.**\n\
    \  - termination_code (string) -- The termination code of the task run. **Not\
    \ populated for rows emitted before late August 2024.**\nDiscovered: 2026-04-30\
    \ 11:10"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.access_control.job_task_run_timeline
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: access_control
    databricks.com/table: job_task_run_timeline
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/access_control/job_task_run_timeline
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
