apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: access-control-data-product-information
  title: access_control.data_product_information
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.access_control.data_product_information\n\
    Columns (17):\n  - data_product_name (string)\n  - description (string)\n  - data_product_user_group\
    \ (string)\n  - data_product_kpi (string)\n  - data_product_critical_fields (string)\n\
    \  - src_tables (string)\n  - src_column (string)\n  - refresh_rate (string)\n\
    \  - business_unit (string)\n  - user_group (string)\n  - data_product_type (string)\n\
    \  - access_link (string)\n  - snow_ticket (string)\n  - contact_for_access (string)\n\
    \  - data_product_version (string)\n  ... +2 more\nDiscovered: 2026-04-30 11:10"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.access_control.data_product_information
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: access_control
    databricks.com/table: data_product_information
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/access_control/data_product_information
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
