apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: access-control-pipeline-update-timeline
  title: access_control.pipeline_update_timeline
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.access_control.pipeline_update_timeline\n\
    Columns (16):\n  - workspace_id (string) -- The ID of the workspace this pipeline\
    \ belongs to.\n  - pipeline_id (string) -- The ID of the pipeline. Unique within\
    \ a workspace.\n  - update_id (string) -- The ID of the pipeline update.\n  -\
    \ update_type (string) -- The type of the pipeline update.\n  - request_id (string)\
    \ -- The ID of the request. Helps to understand how many times an update had to\
    \ be retried/restarted.\n  - run_as_user_name (string) -- The email/ID of the\
    \ service principal whose permissions are used for the job run.\n  - trigger_type\
    \ (string) -- What triggered this update.\n  - trigger_details (struct<job_task:struct<job_id:string,job_task_run_id:string,performance_target:string>>)\
    \ -- The details of the pipeline's trigger.\n  - result_state (string) -- The\
    \ outcome of the pipeline update.\n  - compute (struct<type:string,cluster_id:string>)\
    \ -- Details about the compute resource used in the pipeline update.\n  - period_start_time\
    \ (timestamp) -- The start time for the pipeline update or for the hour. The value\
    \ is stored as a UTC timestamp.\n  - period_end_time (timestamp) -- The end time\
    \ for the pipeline update or for the hour. The value is stored as a UTC timestamp.\n\
    \  - refresh_selection (array<struct<table_catalog:string,table_schema:string,table_name:string>>)\
    \ -- A list of tables to update without fullRefresh.\n  - full_refresh_selection\
    \ (array<struct<table_catalog:string,table_schema:string,table_name:string>>)\
    \ -- A list of tables to update with fullRefresh.\n  - reset_checkpoint_selection\
    \ (array<string>) -- A list of streaming flows to clear the checkpoints for.\n\
    \  ... +1 more\nDiscovered: 2026-04-30 11:11"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.access_control.pipeline_update_timeline
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: access_control
    databricks.com/table: pipeline_update_timeline
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/access_control/pipeline_update_timeline
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
