apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ariba-temp-ariba-projects
  title: ariba.temp_ariba_projects
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.ariba.temp_ariba_projects\n\
    Columns (6):\n  - InternalId (string)\n  - Status (string)\n  - TimeCreated (string)\n\
    \  - TimeUpdated (string)\n  - Title (string)\n  - UniqueId (string)\nDiscovered:\
    \ 2026-04-30 11:14"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.ariba.temp_ariba_projects
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: ariba
    databricks.com/table: temp_ariba_projects
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/ariba/temp_ariba_projects
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
