apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: audit-data-purging-logs
  title: audit.data_purging_logs
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.audit.data_purging_logs\n\
    Columns (9):\n  - run_id (string) -- job run id of the databricks jobs\n  - process_date\
    \ (date) -- The execution date when the data purging is executed\n  - full_table_name\
    \ (string) -- Table name of the purging policy\n  - mode (string) -- inactive\
    \ for only inactive record | age for ageing based\n  - retention_days (int) --\
    \ Number of days for retention threshold\n  - where_clause (string) -- the condition\
    \ of purging the data\n  - matched_count (bigint) -- The counts of recoerds purged\n\
    \  - status (string) -- The status of Purging activity\n  - message (string) --\
    \ Message of the purging activity, Skip or error Messages\nDiscovered: 2026-04-30\
    \ 11:18"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.audit.data_purging_logs
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: audit
    databricks.com/table: data_purging_logs
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/audit/data_purging_logs
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
