apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: br-sap-mpp-bseg
  title: br_sap_mpp.bseg
  description: "Auto-discovered from Databricks Unity Catalog.\nFull name: adani_edl_governance_catalog_dev.br_sap_mpp.bseg\n\
    Columns (195):\n  - MANDT (string) -- Client\n  - BUKRS (string) -- Company Code\n\
    \  - BELNR (string) -- Accounting Document Number\n  - GJAHR (bigint) -- Fiscal\
    \ Year\n  - BUZEI (bigint) -- Number of Line Item Within Accounting Document\n\
    \  - BUZID (string) -- Identification of the Line Item\n  - AUGDT (date) -- Clearing\
    \ Date\n  - AUGCP (date) -- Clearing Entry Date\n  - AUGBL (string) -- Document\
    \ Number of the Clearing Document\n  - BSCHL (string) -- Posting Key\n  - KOART\
    \ (string) -- Account Type\n  - UMSKZ (string) -- Special G/L Indicator\n  - SHKZG\
    \ (string) -- Debit/Credit Indicator\n  - GSBER (string) -- Business Area\n  -\
    \ MWSKZ (string) -- Tax on sales/purchases code\n  ... +180 more\nDiscovered:\
    \ 2026-04-30 11:21"
  tags:
  - databricks
  - auto-discovered
  - unity-catalog
  - sap
  annotations:
    databricks.com/full-table-name: adani_edl_governance_catalog_dev.br_sap_mpp.bseg
    databricks.com/catalog: adani_edl_governance_catalog_dev
    databricks.com/schema: br_sap_mpp
    databricks.com/table: bseg
  links:
  - url: https://adb-2478587080594690.10.azuredatabricks.net/explore/data/adani_edl_governance_catalog_dev/br_sap_mpp/bseg
    title: View in Databricks
    icon: dashboard
spec:
  type: data-table
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake
