apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edl-cicd-pipeline
  description: CI/CD pipeline managing code deployment to Databricks
  tags:
    - cicd
    - gitlab
    - deployment
  links:
    - url: https://gitlab.com/adanidevsecops/ael/enterprise-data-and-ai/ael-enterprise-lakehouse/-/blob/DEV/databricks/jobs/edl_procurement_gold.yml?ref_type=heads
      title: GitLab Pipeline
      icon: github
spec:
  type: service
  lifecycle: production
  owner: edl-governance
  system: enterprise-data-lake